development:
  adapter: postgresql
  encoding: unicode
  database: app_name_development
  pool: 5
  username: app_name_dev
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: app_name_test
  pool: 5
  username: app_name_dev
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: app_name_production
  pool: 5
  username: app_name_dev
  password:
