source 'https://rubygems.org'

gem 'thin'
gem 'rails', '3.2.11'
gem 'pg'

gem 'carrierwave'
gem 'fog'
gem 'mini_magick'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do 
  gem 'debugger'
end

gem 'jquery-rails'
